# Form implementation generated from reading ui file 'texti.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(919, 781)
        Form.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(parent=Form)
        self.frame_left.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_left.setStyleSheet("background-color: rgb(224, 169, 175);\n"
"")
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.frame_info = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_info.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.frame_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_info.setObjectName("frame_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_info)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_info)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_info)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_info)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_info)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.verticalLayout_3.addWidget(self.frame_info)
        self.pushButton_calculate_rascr = QtWidgets.QPushButton(parent=self.frame_left)
        self.pushButton_calculate_rascr.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_calculate_rascr.setStyleSheet("background-color: rgb(181, 213, 202);\n"
"border-radius: 5px;")
        self.pushButton_calculate_rascr.setObjectName("pushButton_calculate_rascr")
        self.verticalLayout_3.addWidget(self.pushButton_calculate_rascr)
        self.pushButton_back = QtWidgets.QPushButton(parent=self.frame_left)
        self.pushButton_back.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_back.setStyleSheet("background-color: rgb(255, 252, 214);\n"
"border-radius: 5px;")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout_3.addWidget(self.pushButton_back)
        self.pushButton_calculate_scraps = QtWidgets.QPushButton(parent=self.frame_left)
        self.pushButton_calculate_scraps.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_calculate_scraps.setStyleSheet("background-color: rgb(181, 213, 202);\n"
"border-radius: 5px;")
        self.pushButton_calculate_scraps.setObjectName("pushButton_calculate_scraps")
        self.verticalLayout_3.addWidget(self.pushButton_calculate_scraps)
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(parent=Form)
        self.frame_right.setStyleSheet("background-color: rgb(224, 169, 175);\n"
"")
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_label_rascr = QtWidgets.QFrame(parent=self.frame_right)
        self.frame_label_rascr.setStyleSheet("background-color: rgb(181, 213, 202);\n"
"border-radius: 5px;")
        self.frame_label_rascr.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_label_rascr.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_label_rascr.setObjectName("frame_label_rascr")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_label_rascr)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_rascr = QtWidgets.QLabel(parent=self.frame_label_rascr)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_rascr.setFont(font)
        self.label_rascr.setScaledContents(False)
        self.label_rascr.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_rascr.setWordWrap(False)
        self.label_rascr.setObjectName("label_rascr")
        self.horizontalLayout_2.addWidget(self.label_rascr)
        self.verticalLayout.addWidget(self.frame_label_rascr)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_right)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 549, 708))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.frame_right)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Информация по заказу:"))
        self.label_3.setText(_translate("Form", "кол-во ткани:"))
        self.label_2.setText(_translate("Form", "можно изготовить изделий:"))
        self.label_5.setText(_translate("Form", "затраты ткани для каждой позиции заказа:"))
        self.label_6.setText(_translate("Form", "общее кол-во затраченной ткани:"))
        self.pushButton_calculate_rascr.setText(_translate("Form", "Рассчитать раскрой"))
        self.pushButton_back.setText(_translate("Form", "Вернуться назад"))
        self.pushButton_calculate_scraps.setText(_translate("Form", "Рассчитать обрезки"))
        self.label_rascr.setText(_translate("Form", "Раскрой изделий"))
